# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  infocadastraiswebapp:
    image: infocadastraiswebapp
    container_name: WebApp
    build:
      context: ./InfoCadastraisWebApp/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - UrlBroker=http://192.168.1.64:5002/Broker

  infocadastraisbroker:
    image: infocadastraisbroker
    container_name: Broker
    build:
      context: ./InfoCadastraisBroker/
      dockerfile: Dockerfile
    ports:
      - 5002:5002